POST http://localhost:8000/api/event/login HTTP/1.1
Content-Type: application/json
Accept: : application/json

{
    "email": "marianna.daniel@example.net",
    "password": "password"
}

### Painel principal (evento atual)
GET http://localhost:8000/api/dashboard HTTP/1.1
Accept: : application/json

### Lista eventos
GET http://localhost:8000/api/dashboard/events HTTP/1.1
Accept: : application/json

### Selecionar evento para gerenciar
POST http://localhost:8000/api/dashboard/select-event HTTP/1.1
Content-Type: application/json
Accept: : application/json

{
    "event_id": "9e0cca07-c1ef-438f-8ae3-a6673cabcca2"
}


### Listar funcionários do evento
GET http://localhost:8000/api/dashboard/staff HTTP/1.1
Accept: : application/json


### Adicionar funcionário ao evento
POST http://localhost:8000/api/dashboard/staff HTTP/1.1
Content-Type: application/json
Accept: : application/json

{
    "name": "Fulano",
    "email": "fulano@example.com",
    "role": "segurança"
}


### Remover funcionário
DELETE http://localhost:8000/api/dashboard/staff/ID_DO_FUNCIONARIO HTTP/1.1
Accept: : application/json


### Listar visitantes
GET http://localhost:8000/api/dashboard/visitors HTTP/1.1
Accept: : application/json


### Cadastrar visitante
POST http://localhost:8000/api/dashboard/visitors HTTP/1.1
Content-Type: application/json
Accept: : application/json

{
    "name": "Visitante Teste",
    "email": "visitante@example.com"
}

###  Reenviar QR Code para visitante
POST http://localhost:8000/api/dashboard/visitors/ID_DO_VISITANTE/resend HTTP/1.1
Accept: : application/json


